# Triatomic molecules

Now we will look at a model of a linear triatomic molecule with one central mass $M$ attached to two peripheral masses $m$. If the molecule is linear, we can approximate this as three masses attached by two springs of constants $k_{12}$ and $k_{23}$. 

The Lagrangian for the general case is

$$
L = \frac{1}{2}m_1 \dot{x}_1^2 + \frac{1}{2}m_2 \dot{x}_2^2 + \frac{1}{2}m_3 \dot{x}_3^2 - \frac{1}{2}\left[ k_{12}(x_1-x_2)^2 + k_{23}(x_2-x_3)^2\right]
$$

This leads to equations of motion

$$
m_1 \ddot{x}_1 = -k_{12} x_1 + k_{12}x_2
$$

$$
m_2 \ddot{x}_2 = k_{12}x_1 - (k_{12} + k_{32})x_2 + k_{23}x_3
$$

$$
m_3 \ddot{x}_3 = -k_{23}x_3 + k_{23}x_2
$$

We can write this as a matrix equation: 

$$
M \ddot{\vec{x}}= -K\vec{x}
$$

This is a generalized eigenvalue problem. We need to solve

$$
K \vec{x} = \omega^2M\vec{x}
$$

We can then let $k_{12} = k_{23} = K$ and $m_1 = m_3 = m, m_2 = M$, and can compute the eigenvalues and eigenvectors directly to obtain: 

$$
\omega_1^2 = 0, \omega_2^2 = \frac{K}{m}, \omega_3^2 = \frac{K}{m}\left(1 + \frac{2m}{M}\right)
$$

$$
\vec{x}_1 = a_1\left( 1, 1, 1\right)
$$

$$
\vec{x}_2 = a_2\left( 1, 0, -1\right)
$$

$$
\vec{x}_3 = a_3\left( 1, -2m/M, 1\right)
$$

So let's compute those numerically. 

In [1]:
import numpy as np
from scipy.linalg import eig

### Make a diagonal matrix for the masses

In [2]:
M = np.diag([1.,2.,1.])

In [3]:
M

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 1.]])

### Make a non-diagonal matrix for the spring constants

In [4]:
k12 = 1.0
k23 = 1.0

In [5]:
K = np.array([
    [   k12,    -k12,       0.0     ],
    [   -k12,   k12 + k23,  -k23    ],
    [   0.0,    -k23,       k23     ]
])

In [6]:
K

array([[ 1., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])

### Calculate the eigenvalues and eigenvectors 

We use the `numpy` funciton 

In [7]:
omega,v = eig(K,M)

In [8]:
print("Eigenvalues : ")
print (omega)

Eigenvalues : 
[-3.55908143e-17+0.j  1.00000000e+00+0.j  2.00000000e+00+0.j]


In [9]:
print("Eigenvectors:")
print(v)

Eigenvectors:
[[-5.77350269e-01  7.07106781e-01  5.77350269e-01]
 [-5.77350269e-01 -6.23947842e-17 -5.77350269e-01]
 [-5.77350269e-01 -7.07106781e-01  5.77350269e-01]]
