In [1]:
import numpy as np
from scipy import linalg

In [2]:

print (" Unbalanced Wheatstone bridge equations")
print (" --------------------------------------")

v0 = 1.5
r1 = 100.
r2 = r1
r3 = 150.
rx = 120.
ra = 1000.
rv = 10.

v = np.zeros((3, 1))       # column vector with 3 rows
v[0,0] = v0
print ('v = ')
print (v)

R = np.zeros((3, 3))       # 3x3 resistance matrix
R[0,0] = r1 + rv      # set components using slicing notation
R[0,1] = r2
R[0,2] = rv

R[1,0] = r1 + ra
R[1,1] = -ra
R[1,2] = -r3

R[2,0] = rx + ra       # or use subscripting notation
R[2,1] = -r2 - rx - ra
R[2,2] = rx

print ('R = ')
print (R)


 Unbalanced Wheatstone bridge equations
 --------------------------------------
v = 
[[1.5]
 [0. ]
 [0. ]]
R = 
[[  110.   100.    10.]
 [ 1100. -1000.  -150.]
 [ 1120. -1220.   120.]]


In [3]:



i = np.linalg.solve(R, v)
print (" Solution using Gauss-Jordan elimination")
print (" i = ", i)


# find the other currents
print (" i_a = i_1 - i_2 = " + str(i[0][0] - i[1][0]))
print (" i_v = i_1 + i_3 = " + str(i[0][0] + i[2][0]))
print (" i_x = i_1 - i_2 + i_3 = " + str(i[0][0] - i[1][0] + i[2][0]))




 Solution using Gauss-Jordan elimination
 i =  [[0.00693364]
 [0.00686499]
 [0.00508009]]
 i_a = i_1 - i_2 = 6.86498855835254e-05
 i_v = i_1 + i_3 = 0.012013729977116704
 i_x = i_1 - i_2 + i_3 = 0.0051487414187643


In [4]:

p,l,u = linalg.lu(R)
print (" LU Decompositon")
print("p:")
print(p)
print("l:")
print(l)
print("u:")
print(u)



 LU Decompositon
p:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
l:
[[1.         0.         0.        ]
 [0.09821429 1.         0.        ]
 [0.98214286 0.90170593 1.        ]]
u:
[[ 1120.         -1220.           120.        ]
 [    0.           219.82142857    -1.78571429]
 [    0.             0.          -266.2469537 ]]
